from tkinter import *
tk = Tk()
macro = []
tk.geometry("500x200")
frame1 = Frame(tk)
frame2 = Frame(tk)
frame3 = Frame(tk)
frame4 = Frame(tk)
frame1.pack(side = RIGHT)
frame2.pack(side = LEFT)
frame3.pack(side = TOP)
frame4.pack(side = BOTTOM)
A = Button(frame2,text = "A").grid(row=0,column=1)
B = Button(frame2,text ="B").grid(row=0,column=2)
C = Button(frame2,text ="C").grid(row=0,column=3)
D = Button(frame2,text ="D").grid(row=0,column=4)
E = Button(frame2,text ="E").grid(row=0,column=5)
F = Button(frame2,text ="F").grid(row=0,column=6)
G = Button(frame2,text ="G").grid(row=0,column=7)
H = Button(frame2,text ="H").grid(row=0,column=8)
I = Button(frame2,text ="I").grid(row=0,column=9)
J = Button(frame2,text ="J").grid(row=0,column=10)
K = Button(frame2,text ="K").grid(row=0,column=11)
L = Button(frame2,text ="L").grid(row=0,column=12)
M = Button(frame2,text ="M").grid(row=0,column=13)
N = Button(frame2,text ="N").grid(row=0,column=14)
O = Button(frame2,text ="O").grid(row=1,column=0)
P = Button(frame2,text ="P").grid(row=1,column=1)
Q = Button(frame2,text ="Q").grid(row=1,column=2)
R = Button(frame2,text ="R").grid(row=1,column=3)
S = Button(frame2,text ="S").grid(row=1,column=4)
T = Button(frame2,text ="T").grid(row=1,column=5)
U = Button(frame2,text ="U").grid(row=1,column=6)
V = Button(frame2,text ="V").grid(row=1,column=7)
W = Button(frame2,text ="W").grid(row=1,column=8)
X = Button(frame2,text ="X").grid(row=1,column=9)
Y = Button(frame2,text ="Y").grid(row=1,column=10)
Z = Button(frame2,text ="Z").grid(row=1,column=11)
delay = Button(frame3, text="Delay").grid(row=1,column=12)
A-Text = Text()
A.pack()
B.pack()
C.pack()
D.pack()
E.pack()
F.pack()
G.pack()
H.pack()
I.pack()
J.pack()
K.pack()
L.pack()
M.pack()
N.pack()
O.pack()
P.pack()
Q.pack()
R.pack()
S.pack()
T.pack()
U.pack()
V.pack()
W.pack()
X.pack()
Y.pack()
Z.pack()
delay.pack()


#def Acon():


